### ISSUE TITLE
Access to (sub) meshes

### ISSUE THREAD

**Issue by PepaZapletal** [ThomasGorisse/sceneform-android-sdk#118]
Hi,

It's possible to access (sub)meshes of the model somehow?

I see in Renderable model property `submeshCount` but nothing more.

And in RenderableInstance is access only to Materials.

I want to show/hide some meshes in the object.

Related to: https://github.com/google-ar/sceneform-android-sdk/issues/242

**Comment by ThomasGorisse** [comment]
Interesting question.

## My first answer is also a question: **Do you really need those meshes to be in the same glTF file?**

Separating them will match all your requests since you will be able to show/hide them, handle the shadow casting/receiving of each `Renderable` and use the actual Sceneform collision system for physical interactions and raycasting.

You will also have access to ARCore collision raycast (`HitTestResult`) which takes care of the model bounding box for you and which is linked to ARCore `Trackable`s = Planes/AugmentedImages and very soon in Sceneform DepthPoints and InstantPlacements.

In the last Blender versions you can do it very easily at the export time by selecting only visible objects.
![image](https://user-images.githubusercontent.com/6597529/125640889-bbedbd3b-58dd-47ca-8f84-61b2e137b91e.png)

It's not an issue if you are not familiar with Blender, you will only have to
- [Download and open Blender](https://www.blender.org/download/)
- Delete the default new Cube/Light/Camera
![image](https://user-images.githubusercontent.com/6597529/125644823-a26ede08-ce0d-4503-9620-6103288a5d62.png)
- File>Import your .obj,/.fbx/.glTF/.glb (and even a lot more importable formats)
- Export your meshes, objects, materials, animations,... (and even maybe one day, for Sceneform, lights and cameras) as **separed glb files**
![image](https://user-images.githubusercontent.com/6597529/125645442-7b5f077a-67af-4b0c-b870-6d15d0dafe51.png)
- You can keep most parameters as they are.
Simple make sure to check
   - - [x] `Visible Objects` to only export the targeted object
   - - [x] `Apply modifiers` (if your 3D designer is like me and prefers applying at the export time)
   - - [x] `Compression` if you have a quite big model and since [Draco](https://google.github.io/draco/) is supported by [Filament](https://github.com/google/filament)
![image](https://user-images.githubusercontent.com/6597529/125645865-ca7c7ae4-0335-4f5b-8767-459d8cf91bf2.png)

You can than simply use one different `Node` per Renderable.
Parenting them (or not) to another or as much nodes as you want, AR Anchored or not.

## **Your second option** is to access submeshes inside a RenderableInstance but you will have to make direct Filament Managers calls.
Working with Submeshed/Subentities of a Renderable will be **for now** very limited since we mostly object consider a Renderable Entity Instance as a closed parent group with limited access to its children.

But don't worry, there is always a solution without OpenGL and Unity since Sceneform mostly only wrap Filament job.
You will have to go more deeply inside Filament ECS from the Sceneform [`RenderableInstance.getFilamentAsset()`
](https://github.com/ThomasGorisse/sceneform-android-sdk/blob/fe31dd9ae67008d2cb5d4966c30026fd51a9330f/core/src/main/java/com/google/ar/sceneform/rendering/RenderableInstance.java#L229)

I can give you more infos about it but I have to say that today is a sunny bank holiday in France ;-) and that the Filament team will answer you a lot better than me on it (please link your Filament questions to here).

_Editor/Contributor's note: Add the Blender export tutorial to /docs and .README_

**Comment by ThomasGorisse** [comment]
@PepaZapletal Did it covered your needs ?

**Comment by PepaZapletal** [comment]
@ThomasGorisse Thank you a lot for your answer! I sent it to the 3D designer and waiting for his reply. 

I will try to go with your first option (more gltf files).

Maybe can you write some example of how to combine more gltf/glb files?

We are using it now for fences. We have one fence and want to change only the fence panel (filling). (One fence can have many panels/fillings)

Here is for example our current model: https://www.uschovna.cz/zasilka/NOF2TZMFW5U3CP4Y-969/ (now I'm waiting for the new information from the 3D designer)

Thank you a lot for your help!

**Comment by PepaZapletal** [comment]
@ThomasGorisse I tried it with separated files (parenting them) and it looks OK! So I close this issue.
