### ISSUE TITLE
Camera projection problem

### ISSUE THREAD

**Issue by joejoe2** [ThomasGorisse/sceneform-android-sdk#165]
Hi, i am using Scene View without arcore. I found that when i set activity to landscape the scene will become old(stretched ?) while rotating camera. I wonder if this is a camera projection problem ?  And how can I solve this ?

Landscape mode:

https://user-images.githubusercontent.com/39475537/135002660-9cd96307-66d0-42c4-b9c0-2dc9104215a6.mp4

Portrait mode:

https://user-images.githubusercontent.com/39475537/135002738-a7429084-03d2-45c0-9fec-80bc94ba307c.mp4

**Comment by grassydragon** [comment]
Hi!
The vertical field of view of the camera is fixed and the horizontal field of view is calculated based on the aspect ratio.
https://github.com/ThomasGorisse/sceneform-android-sdk/blob/193442f519fa6d1fb64768d47207770444a1c846/core/src/main/java/com/google/ar/sceneform/Camera.java#L50
There is a fish-eye effect in the horizontal orientation because the horizontal field of view becomes much higher than it was in the vertical orientation.
If you want to preserve the fields of view along the short and long sides of the device, you need to calculate the vertical field of view in the horizontal orientation (taking into consideration that the horizontal field of view should be now 90 degrees) and set it using this method:
https://github.com/ThomasGorisse/sceneform-android-sdk/blob/193442f519fa6d1fb64768d47207770444a1c846/core/src/main/java/com/google/ar/sceneform/Camera.java#L123

**Comment by joejoe2** [comment]
@grassydragon Thank for your reply. I got your idea, but how to calculate vertical field of view in the horizontal orientation ?

**Comment by grassydragon** [comment]
First, convert the horizontal field of view to radians.

tan(vertical_fov / 2) = (height / 2) / near
tan(horizontal_fov / 2) = (width / 2) / near

tan(vertical_fov / 2) = tan(horizontal_fov / 2) / width * height

vertical_fov = 2 * atan(tan(horizontal_fov / 2) / width * height)

Finally, convert the vertical field of view to degrees.

**Comment by joejoe2** [comment]
Thanks you very much !  I try your method and it seems to got working, but i am not sure.


https://user-images.githubusercontent.com/39475537/135056018-8117f980-b43f-4c67-af5c-f36a0ebff647.mp4
