### ISSUE TITLE
Exception when no AugmentedImageListener is set

### ISSUE THREAD

**Issue by eschoenawa** [ThomasGorisse/sceneform-android-sdk#177]
I am working with augmented images in my app. However, I manually check for Augmented Images using `ArFrame.getUpdatedTrackables(AugmentedImage::class.java)`. Thus I did not set a listener for Augmented Images. However, without a listener, the app will crash the instant it detects an Augmented Image due to a NullPointerException.

My current workaround is to just set an empty listener. This works but isn't a pretty solution.

**Comment by ThomasGorisse** [comment]
In that case, just use the frame update listener and call this:
https://github.com/ThomasGorisse/sceneform-android-sdk/blob/9a7c9c69609c231feb87df80a375f585af688165/core/src/main/java/com/google/ar/sceneform/ArSceneView.java#L674
Take care of what you are doing each frame since it can result in a very consuming/laggy rendering.
Exemple: Don't try to get the ARCore frame informations outside of Sceneform functions since they create new instances each calls.

And if you appreciated the Sunday evening answer, consider clicking on the sponsor button bellow.
