### ISSUE TITLE
Getting error when applying material colour to 3d model . 

### ISSUE THREAD

**Issue by suryanadiminti99** [ThomasGorisse/sceneform-android-sdk#63]
Error : 
A/libc: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x7c51112448 in tid 4182

My Code : 
My app was crashed after few seconds . @ThomasGorisse @senthil5053 @RGregat 

`MaterialFactory.makeOpaqueWithColor(this,

                new Color(android.graphics.Color.RED)).thenAccept(material1 -> {

            node1.getRenderableInstance().setMaterial(material1);

        });`

**Comment by ThomasGorisse** [comment]
Make a PR

**Comment by ThomasGorisse** [comment]
I'm sorry. I really appreciate to help everyone here but please stop calling :
```
val solution = thomasGorisse.doAllTheWorkForMe(everyday=true, sayHello=false, sayThanks=false)
```

**Comment by suryanadiminti99** [comment]
> I'm sorry. I really appreciate helping everyone here but please stop calling :
> 
> ```
> val solution = thomasGorisse.doAllTheWorkForMe(everyday=true, sayHello=false, sayThanks=false)
> ```
> 
> Other users also need help and I only have 2 hands.

It's okay , I can understand @ThomasGorisse . Thanks for your contribution .

**Comment by ThomasGorisse** [comment]
Just try to make a pull request. It's quite easy from GitHub or directly inside Android Studio:

![image](https://user-images.githubusercontent.com/6597529/117631832-e9b5d100-b17c-11eb-9b93-db9922757b95.png)
Choose your own fork and the rest of the process is quite automated.
![image](https://user-images.githubusercontent.com/6597529/117632047-2681c800-b17d-11eb-8af5-e0c49dce7f91.png)
And don't worry, I'll check your commit and bring modifications if needed.

I really prefer verifying your PR and share the result with the whole community instead of answering every small question.

Sceneform is less hard to understand than it seems.
