### ISSUE TITLE
Is Depth API enabled for this fork of Sceneform?

### ISSUE THREAD

**Issue by AntonClaesson** [ThomasGorisse/sceneform-android-sdk#82]
Is ARCore's Depth API enabled for this fork of Sceneform, or are there any plans to support it in the future?

**Comment by RGregat** [comment]
You can acces the Depth API, but in our fork is the occlusion use case not implemented yet.

```java
public void onUpdate(Frame frame) {
   // Retrieve the depth map for the current frame, if available.
   try {
      mDepthImage = frame.acquireDepthImage();
      // Use the depth map here.
   } catch (NotYetAvailableException e) {
      // This means that depth data is not available yet.
      // Depth data will not be available if there are no tracked
      // feature points. This can happen when there is no motion, or when the
      // camera loses its ability to track objects in the surrounding
      // environment.
   }
}
```

With the DepthImage you can calculate the distance from the camera to the DepthImage or extract depth points to do some sort of reconstruction and so on. 

But I guess you question was regarding the occlusion capability? Well, we could put that on our todo list I guess @ThomasGorisse

**Comment by rudsberg** [comment]
The occlusion capability would be extremely helpful! @RGregat @ThomasGorisse

**Comment by AntonClaesson** [comment]
@RGregat Okay! Yea I was mainly interested in the occlusion capability, as I don't have the skills to implement it myself. It would be an awesome addition if possible

**Comment by ThomasGorisse** [comment]
Please guys, don't ask sensible questions so early. We are still in the morning in France :-)

So... for the Depth API question. The fact is that I already implemented it on RealityCore [here](https://github.com/ThomasGorisse/realitycore/blob/main/realitycore/src/main/java/com/gorisse/thomas/realitycore/ar/ArEnvironment.kt).
As you will see, it was so obvious to use the `frame.takeIf { session.isDepthModeSupported }?.acquireDepthImage()` and pass it to Filament CameraStream, applying the Depth UV map and Camera texture, that I would never though it would work until I launched the test app:

![Screenshot_20210611-120347](https://user-images.githubusercontent.com/6597529/121670333-98676d00-caad-11eb-980f-79740d9eaf54.png)
Except some little artificats it work really great.
I have to say a big thank to @zirman for his work [here](https://github.com/zirman/arcore-filament-example-app)

So now the question is whether or not implementing it in Sceneform

RealityCore just need a little more work to be completely functional but I have to say that Sceneform takes a little time to maintain.

If anyone wants to implement it I can give the 2 .filamat shaders compiled with matc for the Depth and Flat modes.

@RGregat Did you made some tests for the planes detections part with the `DepthMode.AUTOMATIC` ?

**Comment by RGregat** [comment]
* If you hand over the needed files, I could try to implement it in Sceneform @ThomasGorisse 
* Wow, first time I heard about RealityCore. Is there any compatibility with the Sceneform SDK? Anchor, AnchorNodes, etc.? 
* What specifically? Performance wise?

**Comment by ThomasGorisse** [comment]
> If you hand over the needed files, I could try to implement it in Sceneform @ThomasGorisse

It would be awesome and I think that it could be a killing feature since the results I saw was pretty much impressive.

Now the fact is that I tested it in cleaned and well managed coroutines contexts. I'm still afraid of Sceneform forgotten and consuming parts like it could possibly be in the old sfb based [LightProbe](core/src/main/java/com/google/ar/sceneform/rendering/LightProbe.java)(I know I have to move it to Filament IndirectLight to completely remove the still alive sfb code).

In the other hand, Scenform is and will still be mainly used and DepthAPI doesn't just came out so it has to be compatible.

> Wow, first time I heard about RealityCore. Is there any compatibility with the Sceneform SDK? Anchor, AnchorNodes, etc.?

It is more based on the ECS ([Entity Compoment System](https://en.wikipedia.org/wiki/Entity_component_system)) but the usage is quite the same as Sceneform (Scene, parenting,...)).
To be short, ECS allocate a CPU for each Component/Functionality (Transformation, Rendering, Anchoring,...) and instead of having a single instance of a Node with a transformation, rendering, anchoring field, there are one different instance of an Entity (Model, light, anchor,..) in each Component.
Like this, every Component (CPU dedicated) manage is own instance and doesn't care about other instances of the same Entity.
Every component can advance at his own rythme and without conflits since it doesn't share the same Entity instance.
It is used by Filament and Unity. You can have an idea of what it can bring with the Sceneform async mode glTF loading.

Not all the code of RealityCore is pushed right now. I really want to clean and document everything before commiting.

> What specifically? Performance wise?
Performance and memory for sure. More maintainability since I try not to put any wrapper around Filament or ARCore (mostly using Kotlin extensions) so dependencies updates are directly accessibles. And simpler to use I hope.

If you are interested, I will see if I can share the complete code somewhere.
But for right now, I think it is more important to make Sceneform great again.

**Comment by ThomasGorisse** [comment]
@RGregat Here are the Depth and Flat .mat and .filamat files for the corresponding Camera materials:
[https://github.com/ThomasGorisse/realitycore/tree/main/realitycore/assets-sources/materials](https://github.com/ThomasGorisse/realitycore/tree/main/realitycore/assets-sources/materials)
Just have to check if the compiled materials are compatible with the last filament version (It will crash the app if not):
[Filamat VS Matc #4118](https://github.com/google/filament/discussions/4118)

**Comment by RGregat** [comment]
Ok, I tried to hack in the occlusion thingy into Sceneform. The result is currently flickering like hell and my understanding about the whole process is to limited to see why. 
My current approach was to adapt the RealityCore implementation. The result is, that the cameraTexture is stable, but the depthTexture is flickering which effects all rendered models (Plane and gltf models for example). 

* Branch: feature/occlusion_rendering
* I updated the sample-gltf project to test it out
* This Branch is under heavy development.

**Comment by ThomasGorisse** [comment]
I'm not in front of my computer right now.
Can you send a screenrecord?

**Comment by RGregat** [comment]
https://user-images.githubusercontent.com/3974162/121800197-b01b2e80-cc30-11eb-9685-66b7c0d9a46b.mp4

**Comment by ThomasGorisse** [comment]
So cool!!!
Great job @RGregat!

The result is here, that's the main thing!

Don't worry about the flickering it must be a Filament frame skipping at the ’beginFrame()‘ or something related maybe due to a camera stream rendering call just before rendering the model.

@romainguy and @prideout I'm sorry to ask it since you already have a lot of work on Filament but can you give us an hand on that.

It would be awesome if you could have a very quick look at the actual Sceneform code and give us some advice regarding little things that could change our life.

More than confirming that Sceneform is mostly using Filament in the right way, it could prevent the raise of your issues count coming from here.

Thanks

**Comment by ThomasGorisse** [comment]
@RGregat Can you try for test purposes to remove the ‘if‘ before ’beginFrame()‘ in the [Renderer](https://www.github.com/ThomasGorisse/sceneform-android-sdk/tree/master/core%2Fsrc%2Fmain%2Fjava%2Fcom%2Fgoogle%2Far%2Fsceneform%2Frendering%2FRenderer.java)?

**Comment by romainguy** [comment]
Frame skipping won’t cause this issue, the problem comes from somewhere else.

How was depth occlusion implemented? The original Sceneform does it by discarding/blending fragments from the fragment shader after sampling the depth texture provided by ARCore.

**Comment by ThomasGorisse** [comment]
Here is the shader:
```
material {
    name : depth,
    shadingModel : unlit,
    blending : opaque,
    vertexDomain : device,
    parameters : [
        {
            type : samplerExternal,
            name : cameraTexture
        },
        {
            type : sampler2d,
            name : depthTexture
        },
        {
            type : float4x4,
            name : uvTransform
        }
    ],
    requires : [
        uv0
    ]
}

fragment {
    void material(inout MaterialInputs material) {
        prepareMaterial(material);
        material.baseColor.rgb = inverseTonemapSRGB(texture(materialParams_cameraTexture, getUV0()).rgb);
        vec2 packed_depth = texture(materialParams_depthTexture, getUV0()).xy;
        float depth_mm = dot(packed_depth, vec2(255.f, 256.f * 255.f));
        vec4 view = mulMat4x4Float3(getClipFromViewMatrix(), vec3(0.f, 0.f, -depth_mm / 1000.f));
        float ndc_depth = view.z / view.w;
        gl_FragDepth = 1.f - ((ndc_depth + 1.f) / 2.f);
    }
}

vertex {
    void materialVertex(inout MaterialVertexInputs material) {
        material.uv0 = mulMat4x4Float3(materialParams.uvTransform, vec3(material.uv0.x, material.uv0.y, 0.f)).xy;
    }
}
```
And the actual @RGregat [implementation](https://github.com/ThomasGorisse/sceneform-android-sdk/commit/34459bdf3a5e8a326641ad6593f880986f6bd627)

**Comment by ThomasGorisse** [comment]
@grassydragon Does the fragment shader looks OK for you?

**Comment by grassydragon** [comment]
Maybe `ndc_depth` is already inverted by the projection matrix? I not sure if it is the same in Filament as in OpenGL.

**Comment by RGregat** [comment]
@ThomasGorisse Nothing changed if I remove the if Statement.
@grassydragon you mean `gl_FragDepth = 1.f - ((ndc_depth + 1.f) / 2.f);` to `gl_FragDepth = ((ndc_depth + 1.f) / 2.f);` ? I tried it and the result is even worse.

**Comment by grassydragon** [comment]
@RGregat
Yes, thank you for testing this. Then everything looks fine in the material.

**Comment by ThomasGorisse** [comment]
I'm also working on it to find out where does it could come from.

**Comment by RGregat** [comment]
> I'm also working on it to find out where does it could come from.

Ok cool, I hope you find something. 
And please bear with me, the current implementation is just to get it to work :)

**Comment by ThomasGorisse** [comment]
OK. So I have tested a lot of things (Rendering order, frame skipping, frame rate,...) and I have to say I didn't find anything so far.

BUT, while trying to debug the totally closed ARCore part (obfuscated java code, no access to the sources, no access to the javadoc.jar,...) I noticed this:
`2021-06-14 21:29:22.860 25667-25901/com.google.ar.sceneform.samples.gltf W/native: plane_estimator.cc:671 Got a new plane, id: 16, with a invalid statistics.`
```
2021-06-14 21:29:22.779 25667-25667/com.google.ar.sceneform.samples.gltf D/ArSceneView: recalculateOcclusion
2021-06-14 21:29:22.779 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane - : depthImage.getTimestamp() : 467308607008427
2021-06-14 21:29:22.779 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane - : depthImage.getWidth() : 160
2021-06-14 21:29:22.779 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane - : depthImage.getHeight() : 90
2021-06-14 21:29:22.780 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane : com.google.ar.core.l@e9f013a
2021-06-14 21:29:22.780 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane.getBuffer().get(0) : -26
2021-06-14 21:29:22.780 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane.getRowStride() : 320
2021-06-14 21:29:22.780 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane.getPixelStride() : 2
2021-06-14 21:29:22.780 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane : ICI
2021-06-14 21:29:22.832 25667-25667/com.google.ar.sceneform.samples.gltf E/native: hit_test.cc:428 generic::internal: No point hit.
2021-06-14 21:29:22.845 25667-25667/com.google.ar.sceneform.samples.gltf D/ArSceneView: recalculateOcclusion
2021-06-14 21:29:22.845 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane - : depthImage.getTimestamp() : 467308640268636
2021-06-14 21:29:22.845 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane - : depthImage.getWidth() : 160
2021-06-14 21:29:22.845 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane - : depthImage.getHeight() : 90
2021-06-14 21:29:22.845 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane : com.google.ar.core.l@8ef61eb
2021-06-14 21:29:22.845 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane.getBuffer().get(0) : -29
2021-06-14 21:29:22.845 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane.getRowStride() : 320
2021-06-14 21:29:22.845 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane.getPixelStride() : 2
2021-06-14 21:29:22.846 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane : ICI
2021-06-14 21:29:22.860 25667-25901/com.google.ar.sceneform.samples.gltf W/native: plane_estimator.cc:671 Got a new plane, id: 16, with a invalid statistics.
2021-06-14 21:29:22.868 25667-25667/com.google.ar.sceneform.samples.gltf E/native: hit_test.cc:428 generic::internal: No point hit.
2021-06-14 21:29:22.874 25667-25667/com.google.ar.sceneform.samples.gltf D/ArSceneView: recalculateOcclusion
2021-06-14 21:29:22.874 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane - : depthImage.getTimestamp() : 467308691075844
2021-06-14 21:29:22.874 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane - : depthImage.getWidth() : 160
2021-06-14 21:29:22.874 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane - : depthImage.getHeight() : 90
2021-06-14 21:29:22.874 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane : com.google.ar.core.l@ba89de1
2021-06-14 21:29:22.874 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane.getBuffer().get(0) : -28
2021-06-14 21:29:22.874 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane.getRowStride() : 320
2021-06-14 21:29:22.874 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane.getPixelStride() : 2
2021-06-14 21:29:22.874 25667-25667/com.google.ar.sceneform.samples.gltf I/System.out: plane : ICI
```

The problem is that I don't know if the plane with a invalid statistics is returned or not by  `currentFrame.acquireDepthImage()`
If the returned `depthImage` is not `null`, I don't have access to anything telling me it's actually invalid (I check the first byte on the plane buffer but nothing consistent with the image invalidity).

Second possibility, the incorrect depthImage is not returned by ARCore but, @RGregat, I didn't figured out what's happening to the CameraTexture if no new occlusion on a frame is applied ?

**Comment by RGregat** [comment]
Ok strange, I mean the cameraTexture is not flickering, but everything else which is rendered on top of it. I need a better understanding how the rendering actually works here. For example what is rendered on the DeptTexture, is it only the depth image or all rendered Elements like the grid or loaded models as well? Maybe we overlook something simple here. 
I will continue tomorrow.

**Comment by ThomasGorisse** [comment]
Note 1: The invalid plane is happening at an approximate medium of 1/10 Frames
Note 2: I will go for collider refreshing on renderables check but  when I look precisely at the artifacts, it makes me feel like some real objects borders are mis—recognized and a complete centered block appear to be so near that is completely occlude behind Renderable.

Anyone who wants to make the test of rendering the actual depthImage color with le last commit in the Depth branch ?

We also on the AugmentedFaceNode which is made @fvito here: #72

And the update to Filament 1.10.2 to check some great new materials.

**Comment by ThomasGorisse** [comment]
> Ok strange, I mean the cameraTexture is not flickering, but everything else which is rendered on top of it. I need a better understanding how the rendering actually works here. For example what is rendered on the DepthTexture, is it only the depth image or all rendered Elements like the grid or loaded models as well? Maybe we overlook something simple here.
> I will continue tomorrow.

Maybe I should make a quick audio or video to explain how is Sceneform mainly done (I'm not an expert), how is RealityCore done and why I really think that after the DepthAPI and the AugmentedFaceNode, a moving forward to a complete ECS mixed with Kotlin AR/3D View SDK could be a paradise to use and maintain

**Comment by grassydragon** [comment]
I really like that RealityCore is using ECS and Kotlin extensions. I think it will be easier to understand than Sceneform if there is no additional wrapper on top of existing ECS in Filament.

**Comment by ThomasGorisse** [comment]
The big issue with Sceneform is that it was originally based on the sfb and then updated to Filament format.
So wrappers and multiple implementations of the same interface are used everywhere to handle its 2 history "life".
One other very frustrating thing comes from the fact that we only have access to the code of new born part (moving fully to Filament). Everything before the 1.1.16 is private and for example, we are currently trying to make the 1.1.15 AugmentFaceNode available on the 1.1.18 but we don't have access to the core class of it. So we must make it from scratch without any resources.
That should be OK since with a little research and some knowledge about the bones matrices, it's not difficult to make it work with ARCore and Filament but the nightmare begins when you have to integrate it in the middle of "IRenderableInternalData" "RenderableInternalData", "FilamentRenderableInternalData", "Renderable", "RenderableInstance", ...
Whereas in Realitycore everything can be done in an AugmentedFacesEntity without  any modifications elsewhere since it only has to tell overs parts what it he is supposed to do (Transformation, Rendering, Anchoring). Other parts of the SDK only has to know which entity exist in the Scene.
If a global transformation appears in the Scene, all entities of the Scene with a Transformation Component registered are aware.
A good example for this is a Light and a Model implementation.
They both have a lot of common: Transformation (Position, Rotation, Scale), Anchoring ("give me an ARCore anchor, I'll place myself in the Scene"), entity parenting,... but the first may be a Filament ‘IndirectLight‘ and the second a ‘FilamentInstance‘
So what should my Light and Model class extends ?
In an ECS the answer is Entity and nothing else.
The specific parts are handled by registered instances components on the Light and Model class.
This could look strange coming from java hierarchical developer point of view but in a 3D engine context that makes a lot of sense.

All that to say that I was originally thinking of not bringing the last ARCore functionalities to Sceneform due to the time it takes to debug small little artifacts like this and be more concentrated on the RealityCore releasing.

**Comment by RGregat** [comment]
Watch this, I write later more about it!

https://user-images.githubusercontent.com/3974162/122026632-b1805e80-cdca-11eb-8b33-14c9b3ec9c74.mp4

**Comment by ThomasGorisse** [comment]
How did you managed to skip the invalid ARCore Depth Images ?

**Comment by ThomasGorisse** [comment]
OK, I saw your commit and I have to say that this makes me made again against how ARCore is lost in the the '90s concerning the open sourcing of an SDK.
Keeping the core sources internal is one thing I can understand but in that case, a big effort have to be made concerning the documentation.
How are we supposed to know what you found with just this documentation: [Use Depth in your Android app](https://developers.google.com/ar/develop/java/depth/developer-guide#acquire_depth_images)

**Comment by RGregat** [comment]
Ok guys this is the story
After a few more poking I eventually started the CPU-Profiler to see how often my depth texture update function is called and what I got was this here

 
![image](https://user-images.githubusercontent.com/3974162/122032833-489be500-cdd0-11eb-9513-0fae6007b5c0.png)


You notice the two big spikes and a few smaller spikes? Looking a little bit more closer I noticed that the PlaneRenderer update is called more often than the depth texture update. But both parts are called on onBeginFrame. Then I thought that maybe not for every frame a new DepthImage is supplied, which resulted into this updated Code

```java
try {
          Image depthImage = currentFrame.acquireDepthImage();
          if(this.depthImage == null)
            this.depthImage = depthImage;
          if(depthImage.getTimestamp() > this.depthImage.getTimestamp()) {

            this.depthImage.close();
            this.depthImage = depthImage;
          }
          Log.d("ArSceneView", "recalculateOcclusion");
          cameraStream.recalculateOcclusion(depthImage);
        } catch (NotYetAvailableException e) {

        }
```

And yeah that worked and I guess it is not an issue to use the old DepthImage if no new DepthImage is available.

I have to test this a little bit, but if the result is stable I can start to wirte the API for it.

**Comment by ThomasGorisse** [comment]
Great job @RGregat !!!

**Comment by RGregat** [comment]
Very interesting, my assumption was not correct and the fix just a lucky move :). The real reason is the ByteBuffer you can retrieve from the DepthImage. When the DeptImage.close() function is called the associated ByteBuffer is invalid. For example if I do this 

```java
public ByteBuffer clone(ByteBuffer original) {
        ByteBuffer clone = ByteBuffer.allocate(original.capacity());
        original.rewind();//copy from the beginning
        clone.put(original);
        original.rewind();
        clone.flip();
        return clone;
}

public void updateDepthTexture(Image depthImage) {
    if (filamentTexture == null)
        return;

    IEngine engine = EngineInstance.getEngine();

    Image.Plane plane = depthImage.getPlanes()[0];
    ByteBuffer buffer = plane.getBuffer();

    ByteBuffer clonedBuffer = clone(buffer);

    pixelBufferDescriptor = new Texture.PixelBufferDescriptor(
            clonedBuffer,
            Texture.Format.RG,
            Texture.Type.UBYTE,
            1,
            0,
            0,
            0,
            handler,
            null
     );

     filamentTexture.setImage(
            engine.getFilamentEngine(),
            0,
            pixelBufferDescriptor
     );
}
```

```java
protected boolean onBeginFrame(long frameTimeNanos) {
   ...
   try(Image depthImage = currentFrame.acquireDepthImage()) {
       cameraStream.recalculateOcclusion(depthImage);
   } catch (NotYetAvailableException e) {
   }
}
```

I get the same non flickering result. I guess this approach is better, because the other approach keeps a reference to the frame if I understood the .close() method correctly. The question is if the ByteBuffer copy really is a better option :D

**Comment by RGregat** [comment]
I would say the basic implementation is done and I created a PR for you. 
I made the Material and Texture creation dependent on the session config. 
The sample-gltf Sample Project is updated to enable the DepthMode, but feel free to test the implementation on other projects!

The next step might be to add something like a toggle to enable or disable the Occlusion during runtime, if this is even possible.

**Comment by ThomasGorisse** [comment]
> I would say the basic implementation is done and I created a PR for you.

OK. I merge as quick as possible

> I made the Material and Texture creation dependent on the session config.

Perfect

> The sample-gltf Sample Project is updated to enable the DepthMode, but feel free to test the implementation on other 
projects!

Can you make a separate module called sample-depth?
sample-gtlf is meant to be a very basic sample and I prefer not having issue reports telling that the model is not completely visible on the screen ;-)

> The next step might be to add something like a toggle to enable or disable the Occlusion during runtime, if this is even possible.

The great mystery of ARCore config at runtime. I'll make tests and ask for it on the ARCore repo.

**Comment by RGregat** [comment]
* I updated the initial PR comment to give more information about the possible settings and the outcome.
* I added a separate project called sample-depth.
* You can disable the now the occlusion feature even if the DepthMode is set to AUTOMATIC or RAW_DEPTH_ONLY

The PR is on a good way, but it needs a few more tests in my opinion.

**Comment by RGregat** [comment]
I like the Panda :)

**Comment by RGregat** [comment]
> Why cloning the ByteBuffer instead of not closing the DepthImage until a new valid one arrive.
> In my point of view it will cost less than cloning the buffer.
> 
> Tell me, as soon as it seems ready for you. I'll make a last check and merge your code.
> 
> The 1.19.0 will be awesome with the Depth, the VideoNode from @Venthorus (#83), the plane renderer fixes and all the optimizations.
> 
> We will wait for 1.19.1 to add the AugmentedFaceNode from @fvito if we figure out a good way to link the bones matrix.
> 
> Thanks to all contributors and answerers.

A small addition to your question about the ByteBuffer copy. I looked into a sample Project from the ARCore-Samples about the Raw-DepthAPI and they did something similar, they don't keep a reference of the DepthImage. So that doesn't mean that it is correct haha. 

https://github.com/google-ar/arcore-android-sdk/blob/2b18171d0aacd999106818e400fae90a4c439e73/samples/raw_depth_java/app/src/main/java/com/google/ar/core/examples/java/rawdepth/Renderer.java#L125

https://github.com/google-ar/arcore-android-sdk/blob/2b18171d0aacd999106818e400fae90a4c439e73/samples/raw_depth_java/app/src/main/java/com/google/ar/core/examples/java/rawdepth/DepthData.java#L53

The `try/catch` is called with a resource `try(resource)...` and that makes sure to auto close the resource. 

So yeah I guess it's a valid approach with the copy process.
